#include "GameServerPacketsNames.h"

namespace l2 {

struct PacketName {
	const char * m_name;
	unsigned char m_id;
};

static PacketName g_packet_name_table[] = {
	{ "Die", 0x00 },
	{ "Revive", 0x01 },
	{ "AttackOutOfRange", 0x02 },
	{ "AttackInCoolTime", 0x03 },
	{ "AttackDeadTarget", 0x04 },
	{ "SpawnItem", 0x05 },
	{ "SellList", 0x06 },
	{ "BuyList", 0x07 },
	{ "DeleteObject", 0x08 },
	{ "CharacterSelectionInfo", 0x09 },
	{ "LoginFail", 0x0A },
	{ "CharacterSelected", 0x0B },
	{ "AbstractNpcInfo", 0x0C },
	{ "NewCharacterSucess", 0x0D },
	{ "NewCharacterFail", 0x0E },
	{ "CharacterCreatesuccess", 0x0F },
	{ "CharacterCreateFail", 0x10 },
	{ "ItemList", 0x11 },
	{ "SunRise", 0x12 },
	{ "SunSet", 0x13 },
	{ "TradeStart", 0x14 },
	{ "TradeStartOk", 0x15 },
	{ "DropItem", 0x16 },
	{ "GetItem", 0x17 },
	{ "StatusUpdate", 0x18 },
	{ "NPCHTMLMessage", 0x19 },
	{ "TradeOwnAdd", 0x1A },
	{ "TradeOtherAdd", 0x1B },
	{ "TradeDone", 0x1C },
	{ "CharacterDeletesuccess", 0x1D },
	{ "CharacterDeleteFail", 0x1E },
	{ "ActionFail", 0x1F },
	{ "SeverClose", 0x20 },
	{ "InventoryUpdate", 0x21 },
	{ "TeleportToLocaton", 0x22 },
	{ "TargetSelected", 0x23 },
	{ "TargetUnselected", 0x24 },
	{ "AutoAttackStart", 0x25 },
	{ "AutoAttackStop", 0x26 },
	{ "SocialAction", 0x27 },
	{ "ChangeMoveType", 0x28 },
	{ "ChangeWaitType", 0x29 },
	{ "ManagePledgePowr", 0x2A },
	{ "CreatePledge", 0x2B },
	{ "AskJoinPledge", 0x2C },
	{ "JoinPledge", 0x2D },
	{ "VersionCheck", 0x2E },
	{ "Init", 0x2E },
	{ "MTL", 0x2F },
	{ "MoveToLocation", 0x2F },
	{ "NPCSay", 0x30 },
	{ "CharInfo", 0x31 },
	{ "UserInfo", 0x32 },
	{ "Attack", 0x33 },
	{ "WithdrawalPledge", 0x34 },
	{ "OustPledgeMembe", 0x35 },
	{ "SetOustPledgeMeber", 0x36 },
	{ "DismissPledge", 0x37 },
	{ "SetDismissPledge", 0x38 },
	{ "AskJoinParty", 0x39 },
	{ "JoinParty", 0x3A },
	{ "WithdrawalParty", 0x3B },
	{ "OustPartyMember", 0x3C },
	{ "SetOustPartyMemer", 0x3D },
	{ "DismissParty", 0x3E },
	{ "SetDismissParty", 0x3F },
	{ "MagicAndSkillList", 0x40 },
	{ "WareHouseDeposiList", 0x41 },
	{ "WareHouseWithdrwList", 0x42 },
	{ "WareHouseList", 0x42 },
	{ "WareHouseDone", 0x43 },
	{ "ShortCutRegister", 0x44 },
	{ "ShortCutInit", 0x45 },
	{ "ShortCutDelete", 0x46 },
	{ "StopMove", 0x47 },
	{ "MagicSkillUse", 0x48 },
	{ "MagicSkillCanceed", 0x49 },
	{ "Say2", 0x4A },
	{ "EquipUpdate", 0x4B },
	{ "DoorInfo", 0x4C },
	{ "DoorStatusUpdate", 0x4D },
	{ "PartySmallWindowAll", 0x4E },
	{ "PartySmallWindowAdd", 0x4F },
	{ "PartySmallWindowDeleteAll", 0x50 },
	{ "PartySmallWindowDelete", 0x51 },
	{ "PartySmallWindowUpdate", 0x52 },
	{ "TradePressOwnOk", 0x53 },
	{ "MagicSkillLaunced", 0x54 },
	{ "FriendAddRequesResult", 0x55 },
	{ "FriendAdd", 0x56 },
	{ "FriendRemove", 0x57 },
	{ "FriendList", 0x58 },
	{ "FriendStatus", 0x59 },
	{ "PledgeShowMembeListAll", 0x5A },
	{ "PledgeShowMembeListUpdate", 0x5B },
	{ "PledgeShowMembeListAdd", 0x5C },
	{ "PledgeShowMembeListDelete", 0x5D },
	{ "MagicList", 0x5E },
	{ "SkillList", 0x5F },
	{ "VehicleInfo", 0x60 },
	{ "FinishRotating", 0x61 },
	{ "SystemMessage", 0x62 },
	{ "StartPledgeWar", 0x63 },
	{ "ReplyStartPledgWar", 0x64 },
	{ "StopPledgeWar", 0x65 },
	{ "ReplyStopPledgeWar", 0x66 },
	{ "SurrenderPledgeWar", 0x67 },
	{ "ReplySurrenderPedgeWar", 0x68 },
	{ "SetPledgeCrest", 0x69 },
	{ "PledgeCrest", 0x6A },
	{ "SetupGauge", 0x6B },
	{ "VehicleDeparture", 0x6C },
	{ "VehicleCheckLoction", 0x6D },
	{ "GetOnVehicle", 0x6E },
	{ "GetOffVehicle", 0x6F },
	{ "TradeRequest", 0x70 },
	{ "RestartResponse", 0x71 },
	{ "MoveToPawn", 0x72 },
	{ "SSQInfo", 0x73 },
	{ "GameGuardQuery", 0x74 },
	{ "L2FriendList", 0x75 },
	{ "L2Friend", 0x76 },
	{ "L2FriendStatus", 0x77 },
	{ "L2FriendSay", 0x78 },
	{ "ValidateLocation", 0x79 },
	{ "StartRotating", 0x7A },
	{ "ShowBoard", 0x7B },
	{ "ChooseInventoryItem", 0x7C },
	{ "Dummy", 0x7D },
	{ "MoveToLocationIVehicle", 0x7E },
	{ "StopMoveInVehice", 0x7F },
	{ "ValidateLocatioInVehicle", 0x80 },
	{ "TradeUpdate", 0x81 },
	{ "TradePressOtherOk", 0x82 },
	{ "FriendAddRequest", 0x83 },
	{ "LogOutOk", 0x84 },
	{ "AbnormalStatusUdate", 0x85 },
	{ "QuestList", 0x86 },
	{ "EnchantResult", 0x87 },
	{ "PledgeShowMembeListDeleteAll", 0x88 },
	{ "PledgeInfo", 0x89 },
	{ "PledgeExtendedInfo", 0x8A },
	{ "SurrenderPersonlly", 0x8B },
	{ "Ride", 0x8C },
	{ "unk", 0x8D },
	{ "PledgeShowInfoUdate", 0x8E },
	{ "ClientAction", 0x8F },
	{ "AcquireSkillList", 0x90 },
	{ "AcquireSkillInfo", 0x91 },
	{ "ServerObjectInfo", 0x92 },
	{ "GMHide", 0x93 },
	{ "AcquireSkillDone", 0x94 },
	{ "GMViewCharacterInfo", 0x95 },
	{ "GMViewPledgeInfo", 0x96 },
	{ "GMViewSkillInfo", 0x97 },
	{ "GMViewMagicInfo", 0x98 },
	{ "GMViewQuestInfo", 0x99 },
	{ "GMViewItemList", 0x9A },
	{ "GMViewWarehouseithdrawList", 0x9B },
	{ "ListPartyWating", 0x9C },
	{ "PartyRoomInfo", 0x9D },
	{ "PlaySound", 0x9E },
	{ "StaticObject", 0x9F },
	{ "PrivateStoreMangeList", 0xA0 },
	{ "PrivateStoreList", 0xA1 },
	{ "PrivateStoreMsg", 0xA2 },
	{ "ShowMinimap", 0xA3 },
	{ "ReviveRequest", 0xA4 },
	{ "AbnormalVisualEfect", 0xA5 },
	{ "TutorialShowHtml", 0xA6 },
	{ "TutorialShowQuetionMark", 0xA7 },
	{ "TutorialEnableCientEvent", 0xA8 },
	{ "TutorialCloseHtml", 0xA9 },
	{ "ShowRadar", 0xAA },
	{ "WithdrawAlliance", 0xAB },
	{ "OustAllianceMemerPledge", 0xAC },
	{ "DismissAlliance", 0xAD },
	{ "SetAllianceCrest", 0xAE },
	{ "AllianceCrest", 0xAF },
	{ "ServerCloseSocket", 0xB0 },
	{ "PetStatusShow", 0xB1 },
	{ "PetInfo", 0xB2 },
	{ "PetItemList", 0xB3 },
	{ "PetInventoryUpdate", 0xB4 },
	{ "AllianceInfo", 0xB5 },
	{ "PetStatusUpdate", 0xB6 },
	{ "PetDelete", 0xB7 },
	{ "DeleteRadar", 0xB8 },
	{ "MyTargetSelected", 0xB9 },
	{ "PartyMemberPosition", 0xBA },
	{ "AskJoinAlliance", 0xBB },
	{ "JoinAlliance", 0xBC },
	{ "PrivateStoreBuyManageList", 0xBD },
	{ "PrivateStoreBuyList", 0xBE },
	{ "PrivateStoreBuyMsg", 0xBF },
	{ "VehicleStart", 0xC0 },
	{ "RequestTimeCheck", 0xC1 },
	{ "StartAllianceWar", 0xC2 },
	{ "ReplyStartAlliaceWar", 0xC3 },
	{ "StopAllianceWar", 0xC4 },
	{ "ReplyStopAllianeWar", 0xC5 },
	{ "SurrenderAllianeWar", 0xC6 },
	{ "SkillCoolTime", 0xC7 },
	{ "PackageToList", 0xC8 },
	{ "CastleSiegeInfo", 0xC9 },
	{ "CastleSiegeAttakerList", 0xCA },
	{ "CastleSiegeDefederList", 0xCB },
	{ "NickNameChanged", 0xCC },
	{ "PledgeStatusChaged", 0xCD },
	{ "RelationChanged", 0xCE },
	{ "EventTrigger", 0xCF },
	{ "MultiSellList", 0xD0 },
	{ "SetSummonRemainTime", 0xD1 },
	{ "PackageSendableList", 0xD2 },
	{ "EarthQuake", 0xD3 },
	{ "FlyToLoaction", 0xD4 },
	{ "BlockList", 0xD5 },
	{ "SpecialCamera", 0xD6 },
	{ "NormalCamera", 0xD7 },
	{ "SkillRemainSec", 0xD8 },
	{ "NetPing", 0xD9 },
	{ "Dice", 0xDA },
	{ "Snoop", 0xDB },
	{ "RecipeBookItemList", 0xDC },
	{ "RecipeItemMakeInfo", 0xDD },
	{ "RecipeShopManagList", 0xDE },
	{ "RecipeShopSellList", 0xDF },
	{ "RecipeShopItemInfo", 0xE0 },
	{ "RecipeShopMsg", 0xE1 },
	{ "ShowCalc", 0xE2 },
	{ "MonRaceInfo", 0xE3 },
	{ "HennaItemInfo", 0xE4 },
	{ "HennaInfo", 0xE5 },
	{ "HennaUnequipList", 0xE6 },
	{ "HennaUnequipInfo", 0xE7 },
	{ "MacroList", 0xE8 },
	{ "BuyListSeed", 0xE9 },
	{ "ShowTownMap", 0xEA },
	{ "ObserverStart", 0xEB },
	{ "ObserverEnd", 0xEC },
	{ "ChairSit", 0xED },
	{ "HennaEquipList", 0xEE },
	{ "SellListProcure", 0xEF },
	{ "GMHennaInfo", 0xF0 },
	{ "RadarControl", 0xF1 },
	{ "ClientSetTime", 0xF2 },
	{ "ConfirmDlg", 0xF3 },
	{ "PartySpelled", 0xF4 },
	{ "ShopPreviewList", 0xF5 },
	{ "ShopPreviewInfo", 0xF6 },
	{ "CameraMode", 0xF7 },
	{ "ShowXMasSeal", 0xF8 },
	{ "EtcStatusUpdate", 0xF9 },
	{ "ShortBuffStatusUpdate", 0xFA },
	{ "SSQStatus", 0xFB },
	{ "PetitionVote", 0xFC },
	{ "AgitDecoInfo", 0xFD },
	{ "UserEx", 0xFE },
};

typedef std::map<unsigned char, const char *> Packet_name_map;

static std::shared_ptr<Packet_name_map> g_packet_name_map;

const char * get_packet_name( unsigned char type ) {
	if( !g_packet_name_map ) {
		g_packet_name_map = std::shared_ptr<Packet_name_map>( new Packet_name_map() );

		for( size_t i = 0; i < sizeof(g_packet_name_table) / sizeof(PacketName) ; ++i ) {
			(*g_packet_name_map)[g_packet_name_table[i].m_id] = g_packet_name_table[i].m_name;
		}
	}

	if( g_packet_name_map->find( type ) != g_packet_name_map->end() ) {
		return (*g_packet_name_map)[type];
	}
	else {
		return "!!! Unknown game packet type !!!";
	}
}

} // namespace l2
